import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import MainLayout from "@/src/components/ui/main-layout";

const sansFont = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const monoFont = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Netuno",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  const fontClasses = `${sansFont.variable} ${monoFont.variable} antialiased`;

  return (
    <html lang="en">
      <body className={fontClasses}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
